services:
  setup-wizard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: picknlight-setup
    ports:
      - "8080:80"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SETUP_COMPLETED=false
      - CONFIG_DIR=/app/config
    privileged: true
    group_add:
      - "996"  # Docker group ID
    networks:
      - picknlight

networks:
  picknlight:
    name: picknlight
    driver: bridge 