services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    user: "root"
    environment:
      - TZ=Europe/Berlin
      - NODE_RED_ENABLE_PROJECTS=true
      - NODE_RED_ENABLE_SAFE_MODE=false
      - NODE_RED_INSTALL_MODULES=node-red-node-mysql,node-red-dashboard,node-red-node-ui-table,node-red-contrib-ui-iro-color-picker
    ports:
      - "{{PORT}}:1880"
    volumes:
      - ./nodered/data:/data
    networks:
      - picknlight
    {{TRAEFIK_LABELS}}

networks:
  picknlight:
    external: true 