version: '3.8'

services:
  partdb:
    container_name: partdb
    image: jbtronics/part-db1:latest
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - APP_SECRET=!ChangeMe!
      - TRUSTED_PROXIES=127.0.0.1,REMOTE_ADDR
      - DATABASE_URL=mysql://root:root@mariadb:3306/partdb
      - INSTANCE_NAME=
      - DEFAULT_LANG=
      - TZ=Europe/Berlin
      - BASE_CURRENCY=EUR
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      - USE_GRAVATAR=0
      - BANNER=Pick'n'Light<br>This will get you sorted
    ports:
      - ":80"
    volumes:
      - ./partdb/data:/var/www/html/public/media
      - ./partdb/uploads:/var/www/html/uploads
    networks:
      - picknlight


networks:
  picknlight:
    external: true 