version: '3.8'

services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - NODE_RED_ENABLE_PROJECTS=true
      - NODE_RED_ENABLE_SAFE_MODE=false
    ports:
      - "8035:1880"
    volumes:
      - ./nodered/data:/data
      - ./nodered/ssh:/root/.ssh
    networks:
      - picknlight
    

networks:
  picknlight:
    external: true 