services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=partdb
      - MYSQL_USER=partdb
      - MYSQL_PASSWORD=root
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    volumes:
      - ./mariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_buffer_pool_size=256M
      - --innodb_log_file_size=64M
      - --max_allowed_packet=128M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot", "--silent"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - picknlight

volumes:
  mariadb_data:
    name: picknlight_mariadb_data

networks:
  picknlight:
    external: true 